name: 'Go: Build and upload artifact'

on:
  release:
    types: [published]

env:
  BOT_TOKEN: ${{ secrets.BOT_TOKEN }}
  GCP_PROJECT_ID: ${{ secrets.GCP_PROJECT_ID }}
  GCS_PATH: ${{ secrets.GCS_PATH }}
  FILE_NAME: 'main' # TODO: Replace name of the resulting file

jobs:
  setup-build-upload:
    name: 'Setup, build and deploy to GCS'
    runs-on: 'ubuntu-latest'
    steps:
      - name: 'Checkout'
        uses: 'actions/checkout@v2'

      - name: 'Set up gcloud CLI'
        uses: 'GoogleCloudPlatform/github-actions/setup-gcloud@master'
        with:
          version: '318.0.0'
          service_account_key: ${{ secrets.GCP_SERVICE_ACCOUNT_KEY }}
          project_id: $GCP_PROJECT_ID

      - name: 'Extract the release version'
        run: echo "APP_VERSION=${GITHUB_REF/refs\/tags\//}" >> $GITHUB_ENV

      - name: 'Set up Go'
        uses: 'actions/setup-go@v2'
        with:
          go-version: '^1.15' # TODO: Adjust to your needs

      - name: 'Build Go'
        run: |- # TODO: Remove the path behind $FILE_NAME if needed
          go env -w GOPRIVATE=github.com/strivecast
          git config --global url."https://$BOT_TOKEN@github.com".insteadOf "https://github.com"
          go build -ldflags="-X 'main.Version=$APP_VERSION'" -o "$FILE_NAME"-"$APP_VERSION" ./server/service

      - name: 'Upload'
        run: gsutil -m cp main "$FILE_NAME" "$GCS_PATH"
